services:
  postgres:
    image: postgres
    volumes:
      - ./postgresql/01_create_chef_database.sql:/docker-entrypoint-initdb.d/01_create_chef_database.sql
      - ./postgresql/02_create_item_chef_database.sql:/docker-entrypoint-initdb.d/02_create_item_chef_database.sql
      - ./postgresql/03_create_barista_database.sql:/docker-entrypoint-initdb.d/03_create_barista_database.sql
      - ./postgresql/04_create_item_barista_database.sql:/docker-entrypoint-initdb.d/04_create_item_barista_database.sql
    environment:
      POSTGRES_PASSWORD: "superpassword"
    ports:
      - "5432:5432"